<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'type'        => 'individual',
                'name'        => 'Md. Rafiqul Islam',
                'father_name' => 'Md. Abul Kashem',
                'mother_name' => 'Hasina Begum',
                'dob'         => '1985-03-12',
                'gender'      => 'male',
                'phone'       => '01711-234567',
                'phone_alt'   => '01811-234567',
                'email'       => 'rafiqul.islam@gmail.com',
                'address'     => 'House 12, Road 5, Dhanmondi',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1209',
                'doc_type'    => 'nid',
                'doc_no'      => '1991234567890',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'referral',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Fatema Akter',
                'father_name' => 'Md. Karim Hossain',
                'mother_name' => 'Rokeya Begum',
                'dob'         => '1990-07-25',
                'gender'      => 'female',
                'phone'       => '01912-345678',
                'phone_alt'   => null,
                'email'       => 'fatema.akter@yahoo.com',
                'address'     => 'Flat 3B, Gulshan Avenue',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1212',
                'doc_type'    => 'nid',
                'doc_no'      => '1992345678901',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'walk_in',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Md. Jahangir Alam',
                'father_name' => 'Md. Shamsul Haque',
                'mother_name' => 'Nasima Begum',
                'dob'         => '1978-11-08',
                'gender'      => 'male',
                'phone'       => '01615-456789',
                'phone_alt'   => '01715-456789',
                'email'       => 'jahangir.alam@hotmail.com',
                'address'     => '45 Uttara Sector 7',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1230',
                'doc_type'    => 'passport',
                'doc_no'      => 'BL0123456',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'facebook_ad',
            ],
            [
                'type'        => 'company',
                'name'        => 'Bashundhara Trading Ltd.',
                'company_name'           => 'Bashundhara Trading Ltd.',
                'company_registration_no'=> 'C-78901/2010',
                'company_tax_id'         => 'TIN-456789012',
                'phone'       => '02-9876543',
                'phone_alt'   => '01711-987654',
                'email'       => 'info@bashundharatrading.com',
                'address'     => 'Bashundhara City, Level 4',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1229',
                'doc_type'    => 'trade_licence',
                'doc_no'      => 'TL-2010-78901',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'other',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Md. Shahabuddin Ahmed',
                'father_name' => 'Md. Lutfur Rahman',
                'mother_name' => 'Amena Khatun',
                'dob'         => '1982-05-19',
                'gender'      => 'male',
                'phone'       => '01812-567890',
                'phone_alt'   => null,
                'email'       => 'shahab.ahmed@gmail.com',
                'address'     => 'Plot 7, Block D, Mirpur 12',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1216',
                'doc_type'    => 'nid',
                'doc_no'      => '1993456789012',
                'kyc_status'  => 'pending',
                'status'      => 'active',
                'source'      => 'referral',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Nasrin Sultana',
                'father_name' => 'Md. Anwarul Hoque',
                'mother_name' => 'Sufia Khatun',
                'dob'         => '1993-09-30',
                'gender'      => 'female',
                'phone'       => '01511-678901',
                'phone_alt'   => '01611-678901',
                'email'       => 'nasrin.sultana@outlook.com',
                'address'     => 'House 88, Road 11, Banani',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1213',
                'doc_type'    => 'nid',
                'doc_no'      => '1994567890123',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'website',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Md. Khorshed Alam',
                'father_name' => 'Md. Mofazzal Hossain',
                'mother_name' => 'Majeda Begum',
                'dob'         => '1975-01-14',
                'gender'      => 'male',
                'phone'       => '01911-789012',
                'phone_alt'   => null,
                'email'       => null,
                'address'     => '23 Agrabad Commercial Area',
                'district'    => 'Chattogram',
                'division'    => 'Chattogram',
                'postal_code' => '4100',
                'doc_type'    => 'nid',
                'doc_no'      => '1995678901234',
                'kyc_status'  => 'pending',
                'status'      => 'active',
                'source'      => 'walk_in',
            ],
            [
                'type'        => 'company',
                'name'        => 'Star Properties & Developers',
                'company_name'           => 'Star Properties & Developers',
                'company_registration_no'=> 'C-12345/2015',
                'company_tax_id'         => 'TIN-123456789',
                'phone'       => '02-8765432',
                'phone_alt'   => '01912-123456',
                'email'       => 'contact@starproperties.com.bd',
                'address'     => 'Suite 501, Eskaton Garden Road',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1000',
                'doc_type'    => 'trade_licence',
                'doc_no'      => 'TL-2015-12345',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'other',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Sharmin Akter Riya',
                'father_name' => 'Md. Nurul Islam',
                'mother_name' => 'Rehana Begum',
                'dob'         => '1996-04-22',
                'gender'      => 'female',
                'phone'       => '01712-890123',
                'phone_alt'   => null,
                'email'       => 'sharmin.riya@gmail.com',
                'address'     => 'Flat 7A, Bashabo Housing',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1214',
                'doc_type'    => 'nid',
                'doc_no'      => '1996789012345',
                'kyc_status'  => 'verified',
                'status'      => 'active',
                'source'      => 'facebook_ad',
            ],
            [
                'type'        => 'individual',
                'name'        => 'Md. Mizanur Rahman',
                'father_name' => 'Md. Abdur Rahim',
                'mother_name' => 'Kulsum Begum',
                'dob'         => '1980-12-05',
                'gender'      => 'male',
                'phone'       => '01612-901234',
                'phone_alt'   => '01812-901234',
                'email'       => 'mizan.rahman@gmail.com',
                'address'     => 'House 3, Road 2, Mohammadpur',
                'district'    => 'Dhaka',
                'division'    => 'Dhaka',
                'postal_code' => '1207',
                'doc_type'    => 'nid',
                'doc_no'      => '1997890123456',
                'kyc_status'  => 'verified',
                'status'      => 'inactive',
                'source'      => 'referral',
            ],
        ];

        foreach ($customers as $data) {
            Customer::updateOrCreate(
            [                'phone' => $data['phone'],
            ],
            [
                'type'                   => $data['type'],
                'name'                   => $data['name'],
                'father_name'            => $data['father_name'] ?? null,
                'mother_name'            => $data['mother_name'] ?? null,
                'date_of_birth'          => $data['dob'] ?? null,
                'gender'                 => $data['gender'] ?? null,
                'phone'                  => $data['phone'],
                'phone_alt'              => $data['phone_alt'] ?? null,
                'email'                  => $data['email'] ?? null,
                'address'                => $data['address'] ?? null,
                'district'               => $data['district'] ?? null,
                'division'               => $data['division'] ?? null,
                'postal_code'            => $data['postal_code'] ?? null,
                'company_name'           => $data['company_name'] ?? null,
                'company_registration_no'=> $data['company_registration_no'] ?? null,
                'company_tax_id'         => $data['company_tax_id'] ?? null,
                'doc_type'               => $data['doc_type'] ?? null,
                'doc_no'                 => $data['doc_no'] ?? null,
                'kyc_status'             => $data['kyc_status'],
                'status'                 => $data['status'],
                'source'                 => $data['source'] ?? null,
                'created_by'             => 1,
                'updated_by'             => 1,
            ]);
        }
    }
}
