<div class="max-w-[700px] mx-auto px-4 py-6"><style>:root{--gap:.6rem}.fc{background:#fff;border:1px solid #e0e0e0;border-radius:6px}.fh{padding:1.2rem 1.5rem;border-bottom:1px solid #f0f0f0}.fh h1{font-size:20px;font-weight:600;margin:0 0 .25rem 0}.fh p{font-size:12px;color:#777;margin:0}.fb{padding:1.5rem}.fg{margin-bottom:1rem}.fg label{display:block;font-size:12px;font-weight:600;margin-bottom:.35rem}.fg input,.fg select,.fg textarea{width:100%;padding:.6rem .8rem;border:1px solid #ddd;border-radius:4px;font-size:13px}.fg input:focus,.fg select:focus,.fg textarea:focus{outline:0;border-color:#0066cc;box-shadow:0 0 0 2px rgba(0,102,204,.1)}.fr{display:grid;grid-template-columns:1fr 1fr;gap:var(--gap)}.fgf{grid-column:1/-1}.ff{padding:1.2rem 1.5rem;border-top:1px solid #f0f0f0;display:flex;gap:.75rem;justify-content:flex-end}.btn{padding:.6rem 1.2rem;border:0;border-radius:4px;font-size:12px;font-weight:600;cursor:pointer}.btn-s{background:#f5f5f5;border:1px solid #ddd}.btn-s:hover{background:#efefef}.btn-p{background:#0066cc;color:#fff}.btn-p:hover{background:#0052a3}.et{color:#d32f2f;font-size:11px;margin-top:.2rem}.bc{font-size:11px;color:#999;margin-bottom:1.5rem;display:flex;gap:.5rem}.bc a{color:#0066cc;text-decoration:0}</style>
    <div class="bc"><a href="{{ route('admin.dashboard') }}">Admin</a><span>/</span><a href="{{ route('admin.account-entries.index') }}">Entries</a><span>/</span><a href="{{ route('admin.account-entries.category', 'payments') }}">Payments</a><span>/</span><span>Supplier Payment</span></div>
    <form wire:submit="save" class="fc">
        <div class="fh"><h1>Supplier Payment</h1><p>Record payment to supplier</p></div>
        <div class="fb">
            <div class="fg"><label>Payable Account *</label><select wire:model="debit_account_id" required><option value="">-- Select --</option>@foreach ($payableAccounts as $a)<option value="{{ $a->id }}">{{ $a->code }} - {{ $a->name }}</option>@endforeach</select>@error('debit_account_id')<div class="et">{{ $message }}</div>@enderror</div>
            <div class="fg"><label>Payment From *</label><select wire:model="credit_account_id" required><option value="">-- Select --</option>@foreach ($paymentAccounts as $a)<option value="{{ $a->id }}">{{ $a->code }} - {{ $a->name }}</option>@endforeach</select>@error('credit_account_id')<div class="et">{{ $message }}</div>@enderror</div>
            <div class="fr"><div class="fg"><label>Amount *</label><input type="number" wire:model="amount" step="0.01" min="0" required /></div><div class="fg"><label>Date *</label><input type="date" wire:model="date" required /></div></div>
            <div class="fr"><div class="fg"><label>Method</label><select wire:model="method"><option value="bank">Bank</option><option value="cash">Cash</option><option value="cheque">Cheque</option></select></div><div class="fg"><label>Reference</label><input type="text" wire:model="reference_no" /></div></div>
            <div class="fr"><div class="fg"><label>Supplier</label><input type="text" wire:model="name" /></div><div class="fg"><label>Phone</label><input type="tel" wire:model="phone" /></div></div>
            <div class="fg fgf"><label>Notes</label><textarea wire:model="notes" rows="3"></textarea></div>
        </div>
        <div class="ff"><a href="{{ route('admin.account-entries.index') }}" class="btn btn-s">Cancel</a><button type="submit" class="btn btn-p" wire:loading.attr="disabled"><span wire:loading.remove>Submit</span><span wire:loading>...</span></button></div>
    </form>
</div>
