// ============================================================
// Shared bank accounts data + helpers
// Used by: Banking Management.html (for balance check)
//          Bank Accounts.html (for the full accounts grid)
// Schema-aligned to bank_accounts table.
// ============================================================

window.ACCOUNTS = [
  {
    id: 1,
    type: "bank",
    bank_name: "Dutch-Bangla Bank Ltd.",
    code: "DBBL-SC-01",
    ac_number: "105.110.0042819",
    branch: "Banani Branch, Dhaka",
    holder_name: "Star Unity Development Ltd.",
    route_code: "090260434",
    swift_code: "DBBLBDDH",
    phone: "+880 2 9882551",
    email: "banani@dbbl.com.bd",
    address: "Plot 67, Block B, Kemal Ataturk Ave, Banani, Dhaka 1213",
    note: "Primary collection account for property sales and customer receivables.",
    status: "active",
    account_id: 12,
    account_code: "1101-01",
    account_name: "Bank - DBBL Sales Collection",
    account_type: "BANK",
    files_count: 3,
    balance: 18457200, currency: "BDT",
    today_inflow: 845000, today_outflow: 120000,
    last_txn_date: "19 May 2026", last_txn_desc: "Property installment received",
    logo: "D", color: "#0c4da2", label: "Sales Collection",
  },
  {
    id: 2,
    type: "bank",
    bank_name: "Prime Bank Ltd.",
    code: "PBL-PAY-01",
    ac_number: "2156.7100.0019.42",
    branch: "Gulshan Branch, Dhaka",
    holder_name: "Star Unity Development Ltd.",
    route_code: "175261534",
    swift_code: "PRBLBDDH",
    phone: "+880 2 9886614",
    email: "gulshan@primebank.com.bd",
    address: "House 18, Road 71, Gulshan-2, Dhaka 1212",
    note: "Dedicated payroll disbursement account. Funded monthly from main account.",
    status: "active",
    account_id: 13, account_code: "1101-02",
    account_name: "Bank - Prime Bank Payroll",
    account_type: "BANK",
    files_count: 2,
    balance: 12450000, currency: "BDT",
    today_inflow: 0, today_outflow: 384200,
    last_txn_date: "18 May 2026", last_txn_desc: "Salary disbursement · May",
    logo: "P", color: "#9c1f2e", label: "Payroll Disbursement",
  },
  {
    id: 3,
    type: "bank",
    bank_name: "Eastern Bank Ltd.",
    code: "EBL-OPS-01",
    ac_number: "1101.0019.4422.78",
    branch: "Mohakhali Branch, Dhaka",
    holder_name: "Star Unity Development Ltd.",
    route_code: "095264528",
    swift_code: "EBLDBDDH",
    phone: "+880 2 8836091",
    email: "mohakhali@ebl.com.bd",
    address: "75 Mohakhali C/A, Dhaka 1212",
    note: "Operational expense account. Used for utilities, rent, supplier payments.",
    status: "active",
    account_id: 14, account_code: "1101-03",
    account_name: "Bank - EBL Operations",
    account_type: "BANK",
    files_count: 1,
    balance: 8920400, currency: "BDT",
    today_inflow: 250000, today_outflow: 142000,
    last_txn_date: "19 May 2026", last_txn_desc: "Office rent paid",
    logo: "E", color: "#1a73a8", label: "Operations & Expense",
  },
  {
    id: 4,
    type: "bank",
    bank_name: "BRAC Bank Ltd.",
    code: "BRAC-USD-01",
    ac_number: "1501.2030.4501.55",
    branch: "Banani Branch, Dhaka",
    holder_name: "Star Unity Development Ltd.",
    route_code: "060261847",
    swift_code: "BRAKBDDH",
    phone: "+880 2 9884286",
    email: "banani@bracbank.com",
    address: "1 Gulshan Avenue, Gulshan-1, Dhaka 1212",
    note: "Foreign currency account for vendor remittances and imports.",
    status: "active",
    account_id: 15, account_code: "1102-01",
    account_name: "Bank - BRAC USD",
    account_type: "BANK",
    files_count: 0,
    balance: 184500, currency: "USD",
    today_inflow: 0, today_outflow: 0,
    last_txn_date: "14 May 2026", last_txn_desc: "Vendor remittance · ABC Imports",
    logo: "B", color: "#e91e25", label: "Foreign Currency · USD",
  },
  {
    id: 5,
    type: "bank",
    bank_name: "City Bank Ltd.",
    code: "CBL-PC-01",
    ac_number: "3501.5008.0091.22",
    branch: "Banani Branch, Dhaka",
    holder_name: "Star Unity Development Ltd.",
    route_code: "225264531",
    swift_code: "CIBLBDDH",
    phone: "+880 2 9892791",
    email: "banani@citybank.com.bd",
    address: "47 Kemal Ataturk Ave, Banani, Dhaka 1213",
    note: "Petty cash float for admin and small office expenses.",
    status: "active",
    account_id: 16, account_code: "1101-04",
    account_name: "Bank - City Petty Cash",
    account_type: "BANK",
    files_count: 1,
    balance: 1245000, currency: "BDT",
    today_inflow: 50000, today_outflow: 16000,
    last_txn_date: "19 May 2026", last_txn_desc: "Stationery purchase",
    logo: "C", color: "#7c2d8e", label: "Petty Cash & Float",
  },
  {
    id: 6,
    type: "mfs",
    bank_name: "bKash Merchant",
    code: "BKASH-MFS-01",
    ac_number: "01700-000000",
    branch: "Mobile Financial Services",
    holder_name: "Star Unity Development Ltd.",
    route_code: "—",
    swift_code: "—",
    phone: "01700-000000",
    email: "merchant@bkash.com",
    address: "bKash Ltd., Shadhinata Tower, Dhaka",
    note: "Customer MFS collection — booking payments and small installments.",
    status: "active",
    account_id: 17, account_code: "1103-01",
    account_name: "MFS - bKash Merchant",
    account_type: "MFS",
    files_count: 0,
    balance: 384210, currency: "BDT",
    today_inflow: 295500, today_outflow: 0,
    last_txn_date: "19 May 2026", last_txn_desc: "Customer booking payment",
    logo: "৳", color: "#e2136e", label: "Customer MFS Collection",
  },
  {
    id: 7,
    type: "bank",
    bank_name: "Islami Bank Bangladesh",
    code: "IBBL-OLD-01",
    ac_number: "2002.4501.0078",
    branch: "Kakrail Branch, Dhaka",
    holder_name: "Star Unity Development Ltd.",
    route_code: "125261428",
    swift_code: "IBBLBDDH",
    phone: "+880 2 8312920",
    email: "kakrail@ibbl.com.bd",
    address: "Islami Bank Tower, Dhaka 1000",
    note: "Closed account — retained for audit trail. Final balance transferred to DBBL.",
    status: "inactive",
    account_id: 18, account_code: "1101-99",
    account_name: "Bank - IBBL (Closed)",
    account_type: "BANK",
    files_count: 4,
    balance: 0, currency: "BDT",
    today_inflow: 0, today_outflow: 0,
    last_txn_date: "31 Dec 2025", last_txn_desc: "Closing transfer",
    logo: "I", color: "#2e7d32", label: "Closed (Archived)",
  },

  // ============ CASH accounts ============
  // type = 'cash' — no bank_name/swift/routing needed.
  // bank_accounts table holds ALL fund-holding accounts: bank, cash, mfs, wallet.
  {
    id: 8,
    type: "cash",
    bank_name: "Head Office Cash",
    code: "CASH-HQ-01",
    ac_number: "—",
    branch: "Banani Head Office",
    holder_name: "Star Unity Development Ltd.",
    route_code: "—",
    swift_code: "—",
    phone: "—",
    email: "—",
    address: "House 42, Road 11, Banani, Dhaka 1213",
    note: "Main petty cash float at head office. Reconciled daily by accounts team. Custodian: Admin Officer.",
    status: "active",
    account_id: 19, account_code: "1100-01",
    account_name: "Cash on Hand - HQ",
    account_type: "CASH",
    files_count: 0,
    balance: 185000, currency: "BDT",
    today_inflow: 5000, today_outflow: 16000,
    last_txn_date: "19 May 2026", last_txn_desc: "Office supplies purchase",
    logo: "৳", color: "#b45309", label: "Office Cash",
  },
  {
    id: 9,
    type: "cash",
    bank_name: "Site Cash · Project Heights",
    code: "CASH-PH-01",
    ac_number: "—",
    branch: "Project Site, Bashundhara",
    holder_name: "Star Unity Development Ltd.",
    route_code: "—",
    swift_code: "—",
    phone: "+880 1715 002 211",
    email: "—",
    address: "Plot 12, Block C, Bashundhara R/A",
    note: "Site cash for daily labor wages and small purchases. Reconciled weekly with site manager. Custodian: Site Engineer.",
    status: "active",
    account_id: 20, account_code: "1100-02",
    account_name: "Cash on Hand - Project Heights",
    account_type: "CASH",
    files_count: 1,
    balance: 95000, currency: "BDT",
    today_inflow: 0, today_outflow: 28000,
    last_txn_date: "19 May 2026", last_txn_desc: "Daily labor wages",
    logo: "৳", color: "#92400e", label: "Site Cash Box",
  },

  // ============ WALLET account ============
  // type = 'wallet' — digital wallets / payment gateways
  {
    id: 10,
    type: "wallet",
    bank_name: "SSLCommerz Merchant",
    code: "WALLET-SSL-01",
    ac_number: "SSL-MID-849201",
    branch: "Online Payment Gateway",
    holder_name: "Star Unity Development Ltd.",
    route_code: "—",
    swift_code: "—",
    phone: "+880 9612 222 333",
    email: "merchant@sslcommerz.com",
    address: "SSL Wireless Ltd., Banani, Dhaka",
    note: "Online payment gateway for customer card payments. Funds settle to DBBL Sales Collection next business day.",
    status: "active",
    account_id: 21, account_code: "1104-01",
    account_name: "Wallet - SSLCommerz Gateway",
    account_type: "WALLET",
    files_count: 2,
    balance: 528400, currency: "BDT",
    today_inflow: 145000, today_outflow: 0,
    last_txn_date: "19 May 2026", last_txn_desc: "Card payment · Booking BR-00148",
    logo: "S", color: "#6d28d9", label: "Payment Gateway",
  },
];

// Look up an account by free-text bank name (used by the balance-check widget
// in Banking Management.html to match a request's bankAccount string).
window.findAccount = function(bankAccountStr) {
  if (!bankAccountStr || /pending/i.test(bankAccountStr)) return null;
  const s = bankAccountStr.toLowerCase();
  for (const a of window.ACCOUNTS) {
    const bank = a.bank_name.toLowerCase();
    const first = bank.split(" ")[0];
    if (s.includes(bank) || s.includes(first)) return a;
  }
  if (s.includes("dbbl") || s.includes("dutch")) return window.ACCOUNTS.find(a => /dutch/i.test(a.bank_name));
  if (s.includes("ebl")  || s.includes("eastern")) return window.ACCOUNTS.find(a => /eastern/i.test(a.bank_name));
  return null;
};

// Mask account number — show first 4 + last 4 only
window.maskAcNo = function(s) {
  if (!s) return "—";
  const clean = String(s).replace(/\s/g, "");
  if (clean.length <= 8) return clean;
  return clean.slice(0, 4) + " •••• " + clean.slice(-4);
};
