<div class="max-w-[700px] mx-auto px-4 py-6"><style>:root{--gap:0.6rem}.form-container{background:#fff;border:1px solid #e0e0e0;border-radius:6px}.form-header{padding:1.2rem 1.5rem;border-bottom:1px solid #f0f0f0}.form-header h1{font-size:20px;font-weight:600;margin:0 0 0.25rem 0}.form-header p{font-size:12px;color:#777}.form-body{padding:1.5rem}.form-group{margin-bottom:1rem}.form-group label{display:block;font-size:12px;font-weight:600;margin-bottom:.35rem}.form-group input,.form-group select,.form-group textarea{width:100%;padding:.6rem .8rem;border:1px solid #ddd;border-radius:4px;font-size:13px}.form-group input:focus,.form-group select:focus,.form-group textarea:focus{outline:0;border-color:#0066cc;box-shadow:0 0 0 2px rgba(0,102,204,.1)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:var(--gap)}.form-group-full{grid-column:1/-1}.form-footer{padding:1.2rem 1.5rem;border-top:1px solid #f0f0f0;display:flex;gap:.75rem;justify-content:flex-end}.btn{padding:.6rem 1.2rem;border:0;border-radius:4px;font-size:12px;font-weight:600;cursor:pointer;transition:all .2s}.btn-secondary{background:#f5f5f5;border:1px solid #ddd}.btn-secondary:hover{background:#efefef}.btn-primary{background:#0066cc;color:#fff}.btn-primary:hover{background:#0052a3}.error-text{color:#d32f2f;font-size:11px;margin-top:.2rem}.breadcrumb{font-size:11px;color:#999;margin-bottom:1.5rem;display:flex;gap:.5rem}.breadcrumb a{color:#0066cc;text-decoration:0}</style>
    <div class="breadcrumb"><a href="{{ route('admin.dashboard') }}">Admin</a><span>/</span><a href="{{ route('admin.account-entries.index') }}">Entries</a><span>/</span><a href="{{ route('admin.account-entries.category', 'receipts') }}">Receipts</a><span>/</span><span>Advance</span></div>
    <form wire:submit="save" class="form-container">
        <div class="form-header"><h1>Record Advance Receipt</h1><p>Record advance received from customer</p></div>
        <div class="form-body">
            <div class="form-group"><label>Received In *</label><select wire:model="debit_account_id" required><option value="">-- Select --</option>@foreach ($paymentAccounts as $a)<option value="{{ $a->id }}">{{ $a->code }} - {{ $a->name }}</option>@endforeach</select>@error('debit_account_id')<div class="error-text">{{ $message }}</div>@enderror</div>
            <div class="form-group"><label>Liability *</label><select wire:model="credit_account_id" required><option value="">-- Select --</option>@foreach ($liabilityAccounts as $a)<option value="{{ $a->id }}">{{ $a->code }} - {{ $a->name }}</option>@endforeach</select>@error('credit_account_id')<div class="error-text">{{ $message }}</div>@enderror</div>
            <div class="form-row"><div class="form-group"><label>Amount *</label><input type="number" wire:model="amount" step="0.01" min="0" required /></div><div class="form-group"><label>Date *</label><input type="date" wire:model="date" required /></div></div>
            <div class="form-row"><div class="form-group"><label>Method</label><select wire:model="method"><option value="cash">Cash</option><option value="bank">Bank</option><option value="cheque">Cheque</option></select></div><div class="form-group"><label>Reference</label><input type="text" wire:model="reference_no" /></div></div>
            <div class="form-row"><div class="form-group"><label>From</label><input type="text" wire:model="name" /></div><div class="form-group"><label>Phone</label><input type="tel" wire:model="phone" /></div></div>
            <div class="form-group form-group-full"><label>Notes</label><textarea wire:model="notes" rows="3"></textarea></div>
        </div>
        <div class="form-footer"><a href="{{ route('admin.account-entries.index') }}" class="btn btn-secondary">Cancel</a><button type="submit" class="btn btn-primary" wire:loading.attr="disabled"><span wire:loading.remove>Submit</span><span wire:loading>...</span></button></div>
    </form>
</div>
