<div x-data x-init="$store.pageName = { name: 'Payroll Details', slug: 'hrm-payroll-view' }">
    <div class="flex flex-wrap items-center justify-between gap-4">
        <div>
            <h1 class="text-lg font-bold text-gray-700">Payroll Details</h1>
            <p class="text-sm text-gray-500">
                {{ $payroll->employee?->name }} - {{ \Carbon\Carbon::createFromDate($payroll->year, $payroll->month, 1)->format('F Y') }}
            </p>
        </div>

        <div class="flex items-center gap-2">
            @can('hrm.payrolls.print')
                <a href="{{ route('admin.hrm.payrolls.payslip.print', $payroll) }}" target="_blank" class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50">
                    Print Payslip
                </a>
            @endcan
            @can('hrm.payrolls.pay')
                @if ($dueAmount > 0)
                    <button type="button" wire:click="openPaymentModal" class="inline-flex items-center rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-gray-800">
                        Add Payment
                    </button>
                @endif
            @endcan
            <a href="{{ route('admin.hrm.payrolls.index') }}" class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50">
                Back
            </a>
        </div>
    </div>

    <div class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-4">
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <p class="text-xs text-gray-500">Gross Salary</p>
            <p class="mt-1 text-xl font-semibold text-gray-800">{{ number_format((float) $payroll->gross_salary, 2) }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <p class="text-xs text-gray-500">Net Salary</p>
            <p class="mt-1 text-xl font-semibold text-gray-800">{{ number_format((float) $payroll->net_salary, 2) }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <p class="text-xs text-gray-500">Total Paid</p>
            <p class="mt-1 text-xl font-semibold text-gray-800">{{ number_format($totalPaid, 2) }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <p class="text-xs text-gray-500">Due</p>
            <p class="mt-1 text-xl font-semibold text-gray-800">{{ number_format($dueAmount, 2) }}</p>
        </div>
    </div>

    <div class="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-3">
        <div class="rounded-2xl border border-gray-200 bg-white p-5 xl:col-span-2">
            <h2 class="text-sm font-semibold text-gray-700">Payroll Information</h2>
            <div class="mt-4 grid grid-cols-1 gap-3 text-sm text-gray-700 md:grid-cols-2">
                <p><span class="text-gray-500">Employee:</span> {{ $payroll->employee?->name }} ({{ $payroll->employee?->employee_id }})</p>
                <p><span class="text-gray-500">Department:</span> {{ $payroll->employee?->department?->name ?: 'N/A' }}</p>
                <p><span class="text-gray-500">Designation:</span> {{ $payroll->employee?->designation?->name ?: 'N/A' }}</p>
                <p><span class="text-gray-500">Payroll Date:</span> {{ optional($payroll->payroll_date)->format('d M, Y') ?: 'N/A' }}</p>
                <p><span class="text-gray-500">Generated By:</span> {{ $payroll->generatedBy?->name ?: 'N/A' }}</p>
                <p><span class="text-gray-500">Approved By:</span> {{ $payroll->approvedBy?->name ?: 'N/A' }}</p>
                <p class="md:col-span-2"><span class="text-gray-500">Notes:</span> {{ $payroll->notes ?: 'N/A' }}</p>
            </div>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <h2 class="text-sm font-semibold text-gray-700">Payment Status</h2>
            <div class="mt-4 space-y-3 text-sm text-gray-700">
                <p>
                    <span class="text-gray-500">Status:</span>
                    <span class="inline-flex rounded-full px-2.5 py-1 text-xs font-medium {{ $payroll->payment_status === 'paid' ? 'bg-emerald-100 text-emerald-700' : ($payroll->payment_status === 'partial' ? 'bg-amber-100 text-amber-700' : 'bg-zinc-100 text-zinc-700') }}">
                        {{ ucfirst($payroll->payment_status) }}
                    </span>
                </p>
                <p><span class="text-gray-500">Payment Date:</span> {{ optional($payroll->payment_date)->format('d M, Y') ?: 'N/A' }}</p>
                <p><span class="text-gray-500">Linked Transaction:</span> {{ $payroll->transaction_id ?: 'N/A' }}</p>
            </div>
        </div>
    </div>

    <div class="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-2">
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <h2 class="text-sm font-semibold text-gray-700">Earnings & Bonus</h2>
            <div class="mt-3 overflow-x-auto">
                <table class="min-w-full">
                    <thead>
                        <tr class="border-b border-gray-100">
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Type</th>
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Label</th>
                            <th class="px-3 py-2 text-right text-xs font-medium text-gray-500">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse (($itemsByType['earning'] ?? collect())->merge($itemsByType['bonus'] ?? collect()) as $item)
                            <tr>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ ucfirst($item->type) }}</td>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ $item->label }}</td>
                                <td class="px-3 py-2 text-right text-sm text-gray-700">{{ number_format((float) $item->amount, 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3" class="px-3 py-8 text-center text-sm text-gray-500">No earning/bonus items found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>

        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <h2 class="text-sm font-semibold text-gray-700">Deductions</h2>
            <div class="mt-3 overflow-x-auto">
                <table class="min-w-full">
                    <thead>
                        <tr class="border-b border-gray-100">
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Label</th>
                            <th class="px-3 py-2 text-right text-xs font-medium text-gray-500">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse ($itemsByType['deduction'] ?? [] as $item)
                            <tr>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ $item->label }}</td>
                                <td class="px-3 py-2 text-right text-sm text-gray-700">{{ number_format((float) $item->amount, 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="2" class="px-3 py-8 text-center text-sm text-gray-500">No deduction items found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-2">
        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <h2 class="text-sm font-semibold text-gray-700">Payroll Payments</h2>
            <div class="mt-3 overflow-x-auto">
                <table class="min-w-full">
                    <thead>
                        <tr class="border-b border-gray-100">
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Date</th>
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Method</th>
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Reference</th>
                            <th class="px-3 py-2 text-right text-xs font-medium text-gray-500">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse ($payroll->payments as $payment)
                            <tr>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ optional($payment->payment_date)->format('d M, Y') }}</td>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ $payment->payment_method ?: 'N/A' }}</td>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ $payment->reference_no ?: 'N/A' }}</td>
                                <td class="px-3 py-2 text-right text-sm font-medium text-gray-700">{{ number_format((float) $payment->amount, 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="px-3 py-8 text-center text-sm text-gray-500">No payroll payments recorded yet.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>

        <div class="rounded-2xl border border-gray-200 bg-white p-5">
            <h2 class="text-sm font-semibold text-gray-700">Advance Adjustments</h2>
            <div class="mt-3 overflow-x-auto">
                <table class="min-w-full">
                    <thead>
                        <tr class="border-b border-gray-100">
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Adjustment Date</th>
                            <th class="px-3 py-2 text-left text-xs font-medium text-gray-500">Advance Status</th>
                            <th class="px-3 py-2 text-right text-xs font-medium text-gray-500">Amount</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse ($payroll->advanceAdjustments as $adjustment)
                            <tr>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ optional($adjustment->adjustment_date)->format('d M, Y') }}</td>
                                <td class="px-3 py-2 text-sm text-gray-700">{{ ucfirst($adjustment->employeeAdvance?->status ?: 'N/A') }}</td>
                                <td class="px-3 py-2 text-right text-sm font-medium text-gray-700">{{ number_format((float) $adjustment->amount, 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3" class="px-3 py-8 text-center text-sm text-gray-500">No advance adjustments used.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div x-cloak x-data="{ open: @entangle('showPaymentModal') }" x-show="open" x-transition class="fixed inset-0 z-50 grid place-content-center bg-black/50 p-4">
        <div class="w-full max-w-2xl rounded-lg bg-white p-6 shadow-lg">
            <div class="flex items-start justify-between">
                <h2 class="text-xl font-bold text-gray-900">Add Payroll Payment</h2>
                <button type="button" @click="open = false; $wire.closePaymentModal()" class="-me-4 -mt-4 rounded-full p-2 text-gray-400 transition hover:bg-gray-50 hover:text-gray-600">
                    <svg xmlns="http://www.w3.org/2000/svg" class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>

            <form wire:submit.prevent="addPayment" class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                    <label class="text-sm font-medium text-gray-700">Payment Date</label>
                    <input type="date" wire:model.defer="payment_date" class="mt-1 h-10 w-full rounded-lg border border-gray-300 px-3 text-sm focus:border-indigo-500 focus:outline-none">
                    @error('payment_date') <p class="mt-1 text-xs text-rose-600">{{ $message }}</p> @enderror
                </div>
                <div>
                    <label class="text-sm font-medium text-gray-700">Amount</label>
                    <input type="number" min="0" step="0.01" wire:model.defer="amount" class="mt-1 h-10 w-full rounded-lg border border-gray-300 px-3 text-sm focus:border-indigo-500 focus:outline-none">
                    <p class="mt-1 text-xs text-gray-500">Due Amount: {{ number_format($dueAmount, 2) }}</p>
                    @error('amount') <p class="mt-1 text-xs text-rose-600">{{ $message }}</p> @enderror
                </div>
                <div>
                    <label class="text-sm font-medium text-gray-700">Payment Method</label>
                    <select wire:model.defer="payment_method" class="mt-1 h-10 w-full rounded-lg border border-gray-300 px-3 text-sm focus:border-indigo-500 focus:outline-none">
                        <option value="">Select method</option>
                        @foreach ($paymentMethods as $method)
                            <option value="{{ $method }}">{{ ucfirst(str_replace('_', ' ', $method)) }}</option>
                        @endforeach
                    </select>
                    @error('payment_method') <p class="mt-1 text-xs text-rose-600">{{ $message }}</p> @enderror
                </div>
                <div>
                    <label class="text-sm font-medium text-gray-700">Reference No</label>
                    <input type="text" wire:model.defer="reference_no" class="mt-1 h-10 w-full rounded-lg border border-gray-300 px-3 text-sm focus:border-indigo-500 focus:outline-none">
                    @error('reference_no') <p class="mt-1 text-xs text-rose-600">{{ $message }}</p> @enderror
                </div>
                <div class="sm:col-span-2">
                    <label class="text-sm font-medium text-gray-700">Notes</label>
                    <textarea wire:model.defer="notes" rows="3" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"></textarea>
                    @error('notes') <p class="mt-1 text-xs text-rose-600">{{ $message }}</p> @enderror
                </div>
                <div class="sm:col-span-2 mt-2 flex justify-end gap-2">
                    <button type="button" @click="open = false; $wire.closePaymentModal()" class="inline-flex items-center rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50">
                        Cancel
                    </button>
                    <button type="submit" class="inline-flex items-center rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-gray-800">
                        Save Payment
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

