{{--
    Excel export — All Client Statement.
    Mirrors the all-client PDF design (company header, info strip, styled data
    table, totals band) but built for Excel.

    Columns: Client · Total Amount · Paid · Outstanding · Overdue Amount ·
             Scheduled (count) · Overdue (count).

    Excel notes:
    · Excel ignores <style>/CSS classes → all styling is inline.
    · mso-number-format forces text on IDs, 2-decimals on money, integers on counts.
--}}
@php
    $colCount = count($report['columns']);
    $moneyKeys = ['total_amount', 'total_paid', 'total_due', 'overdue_amount'];
    $countKeys = ['scheduled_count', 'overdue_count'];

    $ink = '#161616';
    $muted = '#5f5f5f';
    $rule = '#c9c9c9';
    $zebra = '#f4f4f4';
    $head = '#e0e0e0';
@endphp
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:x="urn:schemas-microsoft-com:office:excel"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
    <meta charset="utf-8">
    @php($sheetName = \Illuminate\Support\Str::limit($report['title'] ?? 'Statement', 28, ''))
    @verbatim<!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>@endverbatim{{ $sheetName }}@verbatim</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--><style>td, th { mso-number-format:"\@"; }</style>@endverbatim
</head>
<body>
<table border="0" cellspacing="0" cellpadding="6"
       style="border-collapse:collapse; font-family:Calibri, Arial, sans-serif; font-size:11px; color:{{ $ink }};">

    {{-- ============================ HEADER ============================ --}}
    <tr>
        <td colspan="{{ max($colCount - 1, 1) }}" style="border:none; vertical-align:top;">
            <span style="font-size:18px; font-weight:bold; color:{{ $ink }};">{{ $report['meta']['company_name'] }}</span><br>
            <span style="font-size:10px; color:{{ $muted }};">
                {{ config('company.address') }} · {{ config('company.phone') }} · {{ config('company.email') }}
            </span>
        </td>
        <td style="border:none; text-align:right; vertical-align:top;">
            <span style="font-size:9px; font-weight:bold; letter-spacing:1px; color:{{ $ink }};">STATEMENT</span><br>
            <span style="font-size:14px; font-weight:bold;">{{ $report['title'] ?? 'Statement' }}</span><br>
            <span style="font-size:9px; color:{{ $muted }};">
                Generated: {{ $report['meta']['generated_at'] ?? now()->format('d M Y, H:i') }}<br>
                Generated by: {{ $report['meta']['generated_by'] ?? 'System' }}
            </span>
        </td>
    </tr>

    {{-- thin rule row --}}
    <tr><td colspan="{{ $colCount }}" style="border:none; border-bottom:2px solid {{ $ink }}; height:2px; font-size:1px;">&nbsp;</td></tr>

    {{-- ============================ INFO STRIP ============================ --}}
    <tr>
        <td colspan="{{ max($colCount - 2, 1) }}" style="border:1px solid {{ $rule }}; background:#ffffff;">
            <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">STATEMENT PERIOD</span><br>
            <span style="font-size:11px; font-weight:bold;">{{ $report['meta']['from_date'] ?? '-' }} – {{ $report['meta']['to_date'] ?? '-' }}</span>
        </td>
        <td style="border:1px solid {{ $rule }};">
            <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">CURRENCY</span><br>
            <span style="font-size:11px; font-weight:bold;">BDT</span>
        </td>
        <td style="border:1px solid {{ $rule }}; text-align:right;">
            <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">TOTAL CLIENTS</span><br>
            <span style="font-size:11px; font-weight:bold;">{{ $report['summary']['total_clients'] ?? 0 }}</span>
        </td>
    </tr>

    {{-- spacer --}}
    <tr><td colspan="{{ $colCount }}" style="border:none; height:6px; font-size:1px;">&nbsp;</td></tr>

    {{-- ============================ COLUMN HEADERS ============================ --}}
    <tr>
        @foreach($report['columns'] as $column)
            <th style="border:1px solid {{ $ink }}; background:{{ $head }}; text-align:{{ $column['align'] ?? 'left' }};
                       font-size:9px; font-weight:bold; text-transform:uppercase;">
                {{ $column['label'] }}
            </th>
        @endforeach
    </tr>

    {{-- ============================ DATA ROWS ============================ --}}
    @forelse($report['rows'] as $row)
        <tr style="background:{{ $loop->even ? $zebra : '#ffffff' }};">
            @foreach($report['columns'] as $column)
                @php($key = $column['key'])
                @if($key === 'client_name')
                    <td style="border:1px solid {{ $rule }}; text-align:left;">
                        <span style="font-weight:bold;">{{ $row['client_name'] ?? '-' }}</span><br>
                        <span style="font-size:9px; color:{{ $muted }};">ID: {{ $row['client_display_id'] ?? '-' }}</span>
                    </td>
                @elseif(in_array($key, $moneyKeys))
                    <td style="border:1px solid {{ $rule }}; text-align:right; mso-number-format:'#,##0.00';">
                        {{ number_format((float)($row[$key] ?? 0), 2) }}
                    </td>
                @elseif(in_array($key, $countKeys))
                    <td style="border:1px solid {{ $rule }}; text-align:center; font-weight:bold; mso-number-format:'0';">
                        {{ $row[$key] ?? 0 }}
                    </td>
                @else
                    <td style="border:1px solid {{ $rule }}; text-align:{{ $column['align'] ?? 'left' }};">
                        {{ $row[$key] ?? '-' }}
                    </td>
                @endif
            @endforeach
        </tr>
    @empty
        <tr>
            <td colspan="{{ $colCount }}" style="border:1px solid {{ $rule }}; text-align:center;">No records found.</td>
        </tr>
    @endforelse

    {{-- spacer --}}
    <tr><td colspan="{{ $colCount }}" style="border:none; height:8px; font-size:1px;">&nbsp;</td></tr>

    {{-- ============================ TOTALS BAND ============================ --}}
    <tr>
        <td colspan="{{ $colCount }}" style="border:none; font-size:8px; font-weight:bold; color:{{ $muted }}; text-transform:uppercase;">
            Statement Summary
        </td>
    </tr>
    <tr style="background:{{ $zebra }}; font-weight:bold;">
        <td colspan="{{ max($colCount - 1, 1) }}" style="border:1px solid {{ $ink }}; text-align:right;">Total Amount:</td>
        <td style="border:1px solid {{ $ink }}; text-align:right; mso-number-format:'#,##0.00';">{{ number_format((float)($report['summary']['total_amount'] ?? 0), 2) }}</td>
    </tr>
    <tr style="font-weight:bold;">
        <td colspan="{{ max($colCount - 1, 1) }}" style="border:1px solid {{ $rule }}; text-align:right;">Paid Amount:</td>
        <td style="border:1px solid {{ $rule }}; text-align:right; mso-number-format:'#,##0.00';">{{ number_format((float)($report['summary']['total_paid'] ?? 0), 2) }}</td>
    </tr>
    <tr style="font-weight:bold;">
        <td colspan="{{ max($colCount - 1, 1) }}" style="border:1px solid {{ $rule }}; text-align:right;">Overdue Amount:</td>
        <td style="border:1px solid {{ $rule }}; text-align:right; mso-number-format:'#,##0.00';">{{ number_format((float)($report['summary']['total_overdue_amount'] ?? 0), 2) }}</td>
    </tr>
    <tr style="font-weight:bold;">
        <td colspan="{{ max($colCount - 1, 1) }}" style="border:1px solid {{ $rule }}; text-align:right;">Scheduled / Overdue (count):</td>
        <td style="border:1px solid {{ $rule }}; text-align:right; mso-number-format:'\@';">{{ $report['summary']['total_scheduled_count'] ?? 0 }} / {{ $report['summary']['total_overdue_count'] ?? 0 }}</td>
    </tr>
    <tr style="background:{{ $zebra }}; font-weight:bold;">
        <td colspan="{{ max($colCount - 1, 1) }}" style="border:2px solid {{ $ink }}; text-align:right;">Total Outstanding:</td>
        <td style="border:2px solid {{ $ink }}; text-align:right; mso-number-format:'#,##0.00';">{{ number_format((float)($report['summary']['total_outstanding'] ?? 0), 2) }}</td>
    </tr>

    @if(!empty($report['meta']['notes']))
        <tr><td colspan="{{ $colCount }}" style="border:none; height:8px; font-size:1px;">&nbsp;</td></tr>
        <tr>
            <td colspan="{{ $colCount }}" style="border:none; font-size:9px; color:{{ $muted }};">
                <b>Notes:</b> {{ $report['meta']['notes'] }}
            </td>
        </tr>
    @endif

    {{-- footer --}}
    <tr><td colspan="{{ $colCount }}" style="border:none; height:6px; font-size:1px;">&nbsp;</td></tr>
    <tr>
        <td colspan="{{ $colCount }}" style="border:none; border-top:1px solid {{ $rule }}; font-size:8px; color:{{ $muted }};">
            {{ config('company.name') }} · {{ $report['title'] ?? 'Statement' }} ·
            Generated {{ $report['meta']['generated_at'] ?? now()->format('d M Y, H:i') }}
        </td>
    </tr>
</table>
</body>
</html>
