{{--
    Client Wise Statement — Excel export. Mirrors client-wise-statement-pdf
    (company header, client strip, info strip, data table, totals band) but
    built for Excel: inline styles only, xmlns:x workbook meta, mso-number-format
    to keep IDs as text and money at 2 decimals.
--}}
@php
    $columns = $report['columns'];
    $count = count($columns);
    $customer = $report['customer'] ?? null;
    $moneyKeys = ['amount', 'total_paid', 'total_due'];

    $ink = '#161616';
    $muted = '#5f5f5f';
    $rule = '#c9c9c9';
    $zebra = '#f4f4f4';
    $head = '#e0e0e0';
@endphp
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:x="urn:schemas-microsoft-com:office:excel"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
    <meta charset="utf-8">
    @verbatim
    <!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Client Wise Statement</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->
    <style>td, th { mso-number-format:"\@"; }</style>
    @endverbatim
</head>
<body>
<table border="0" cellspacing="0" cellpadding="6"
       style="border-collapse:collapse; font-family:Calibri, Arial, sans-serif; font-size:11px; color:{{ $ink }};">

    {{-- ============================ HEADER ============================ --}}
    <tr>
        <td colspan="{{ max($count - 1, 1) }}" style="border:none; vertical-align:top;">
            <span style="font-size:18px; font-weight:bold;">{{ $report['meta']['company_name'] }}</span><br>
            <span style="font-size:10px; color:{{ $muted }};">
                {{ config('company.address') }} · {{ config('company.phone') }} · {{ config('company.email') }}
            </span>
        </td>
        <td style="border:none; text-align:right; vertical-align:top;">
            <span style="font-size:9px; font-weight:bold; letter-spacing:1px;">STATEMENT</span><br>
            <span style="font-size:14px; font-weight:bold;">{{ $report['title'] ?? 'Client Wise Statement' }}</span><br>
            <span style="font-size:9px; color:{{ $muted }};">
                Generated: {{ $report['meta']['generated_at'] ?? now()->format('d M Y, H:i') }}<br>
                Generated by: {{ $report['meta']['generated_by'] ?? 'System' }}
            </span>
        </td>
    </tr>
    <tr><td colspan="{{ $count }}" style="border:none; border-bottom:2px solid {{ $ink }}; height:2px; font-size:1px;">&nbsp;</td></tr>

    {{-- ============================ CLIENT STRIP ============================ --}}
    @if($customer)
        <tr><td colspan="{{ $count }}" style="border:none; font-size:8px; font-weight:bold; color:{{ $muted }}; text-transform:uppercase;">Client Details</td></tr>
        <tr>
            <td colspan="{{ max(ceil($count/3), 1) }}" style="border:1px solid {{ $rule }};">
                <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">CLIENT</span><br>
                <span style="font-weight:bold;">{{ $customer['name'] ?? '-' }}</span>
            </td>
            <td colspan="{{ max(ceil($count/3), 1) }}" style="border:1px solid {{ $rule }};">
                <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">CLIENT ID</span><br>
                <span style="font-weight:bold;">{{ $customer['code'] ?? '-' }}</span>
            </td>
            <td colspan="{{ max($count - 2 * ceil($count/3), 1) }}" style="border:1px solid {{ $rule }};">
                <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">PHONE</span><br>
                <span style="font-weight:bold;">{{ $customer['phone'] ?? '-' }}</span>
            </td>
        </tr>
        <tr>
            <td colspan="{{ max(ceil($count/3), 1) }}" style="border:1px solid {{ $rule }};">
                <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">EMAIL</span><br>
                <span style="font-weight:bold;">{{ $customer['email'] ?? '-' }}</span>
            </td>
            <td colspan="{{ max($count - ceil($count/3), 1) }}" style="border:1px solid {{ $rule }};">
                <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">ADDRESS</span><br>
                <span style="font-weight:bold;">{{ $customer['address'] ?? '-' }}</span>
            </td>
        </tr>
    @endif

    {{-- ============================ INFO STRIP ============================ --}}
    <tr>
        <td colspan="{{ max(ceil($count/2), 1) }}" style="border:1px solid {{ $rule }};">
            <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">STATEMENT PERIOD</span><br>
            <span style="font-weight:bold;">{{ $report['meta']['from_date'] ?? '-' }} – {{ $report['meta']['to_date'] ?? '-' }}</span>
        </td>
        <td colspan="{{ max(($count - ceil($count/2)) - 1, 1) }}" style="border:1px solid {{ $rule }}; text-align:right;">
            <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">PROPERTIES</span><br>
            <span style="font-weight:bold;">{{ $report['summary']['total_transactions'] ?? 0 }}</span>
        </td>
        <td style="border:1px solid {{ $rule }}; text-align:right;">
            <span style="font-size:8px; font-weight:bold; color:{{ $muted }};">OUTSTANDING</span><br>
            <span style="font-weight:bold; mso-number-format:'#,##0.00';">{{ number_format((float)($report['summary']['total_outstanding'] ?? 0), 2) }}</span>
        </td>
    </tr>
    <tr><td colspan="{{ $count }}" style="border:none; height:6px; font-size:1px;">&nbsp;</td></tr>

    {{-- ============================ COLUMN HEADERS ============================ --}}
    <tr>
        @foreach($columns as $column)
            @if($column['key'] !== 'actions')
                <th style="border:1px solid {{ $ink }}; background:{{ $head }}; text-align:{{ $column['align'] ?? 'left' }};
                           font-size:9px; font-weight:bold; text-transform:uppercase;">{{ $column['label'] }}</th>
            @endif
        @endforeach
    </tr>

    {{-- ============================ DATA ROWS ============================ --}}
    @forelse($report['rows'] as $row)
        <tr style="background:{{ $loop->even ? $zebra : '#ffffff' }};">
            @foreach($columns as $column)
                @php $key = $column['key'] @endphp
                @if($key === 'actions')
                    {{-- Skip actions column in Excel --}}
                @elseif(in_array($key, $moneyKeys))
                    <td style="border:1px solid {{ $rule }}; text-align:right; mso-number-format:'#,##0.00';">
                        {{ number_format((float)($row[$key] ?? 0), 2) }}
                    </td>
                @else
                    <td style="border:1px solid {{ $rule }}; text-align:{{ $column['align'] ?? 'left' }};">
                        {{ $row[$key] ?? '-' }}
                    </td>
                @endif
            @endforeach
        </tr>
    @empty
        <tr><td colspan="{{ $count }}" style="border:1px solid {{ $rule }}; text-align:center;">No records found.</td></tr>
    @endforelse

    <tr><td colspan="{{ $count }}" style="border:none; height:8px; font-size:1px;">&nbsp;</td></tr>

    {{-- ============================ TOTALS BAND ============================ --}}
    <tr>
        <td colspan="{{ $count }}" style="border:none; font-size:8px; font-weight:bold; color:{{ $muted }}; text-transform:uppercase;">Statement Summary</td>
    </tr>
    @php
        $totals = [
            ['Properties', $report['summary']['total_transactions'] ?? 0, false],
            ['Sale Amount', number_format((float)($report['summary']['total_sale_amount'] ?? 0), 2), true],
            ['Rent Amount', number_format((float)($report['summary']['total_rent_amount'] ?? 0), 2), true],
            ['Total Paid', number_format((float)($report['summary']['total_paid'] ?? 0), 2), true],
            ['Scheduled', $report['summary']['total_scheduled'] ?? 0, false],
            ['Overdue', $report['summary']['total_overdue'] ?? 0, false],
        ];
    @endphp
    @foreach($totals as $i => $total)
        <tr style="background:{{ $i % 2 === 0 ? $zebra : '#ffffff' }}; font-weight:bold;">
            <td colspan="{{ max($count - 1, 1) }}" style="border:1px solid {{ $rule }}; text-align:right;">{{ $total[0] }}:</td>
            <td style="border:1px solid {{ $rule }}; text-align:right; @if($total[2]) mso-number-format:'#,##0.00'; @endif">{{ $total[1] }}</td>
        </tr>
    @endforeach
    <tr style="background:{{ $zebra }}; font-weight:bold;">
        <td colspan="{{ max($count - 1, 1) }}" style="border:2px solid {{ $ink }}; text-align:right;">Total Outstanding:</td>
        <td style="border:2px solid {{ $ink }}; text-align:right; mso-number-format:'#,##0.00';">{{ number_format((float)($report['summary']['total_outstanding'] ?? 0), 2) }}</td>
    </tr>

    {{-- footer --}}
    <tr><td colspan="{{ $count }}" style="border:none; height:6px; font-size:1px;">&nbsp;</td></tr>
    <tr>
        <td colspan="{{ $count }}" style="border:none; border-top:1px solid {{ $rule }}; font-size:8px; color:{{ $muted }};">
            {{ config('company.name') }} · {{ $report['title'] ?? 'Client Wise Statement' }} ·
            Generated {{ $report['meta']['generated_at'] ?? now()->format('d M Y, H:i') }}
        </td>
    </tr>
</table>
</body>
</html>
