<?php

use App\Enums\Accounts\EntryWorkflow;
use App\Enums\Accounts\TransactionType;

return [
    'categories' => [
        'receipts' => [
            'title' => 'Receipts',
            'description' => 'Record money coming into the business',
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M2 12h20"/></svg>',
            'sort' => 10,
        ],
        'payments' => [
            'title' => 'Payments',
            'description' => 'Record money going out of the business',
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M2 12h20"/></svg>',
            'sort' => 20,
        ],
        'transfers' => [
            'title' => 'Transfers & Adjustments',
            'description' => 'Transfer funds or adjust accounts',
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><polyline points="19 12 12 19 5 12"/></svg>',
            'sort' => 30,
        ],
        'opening' => [
            'title' => 'Opening Balances',
            'description' => 'Set initial account balances',
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/></svg>',
            'sort' => 40,
        ],
    ],

    'entries' => [
        // Receipts
        'income' => [
            'title' => 'Income',
            'description' => 'Record general income received',
            'category' => 'receipts',
            'component' => \App\Livewire\Admin\Accounts\Entry\Receipts\IncomeForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::INCOME,
            'permission' => 'accounts.entry.receipts.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 10,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"/></svg>',
            'route' => null,
        ],
        'customer-receipt' => [
            'title' => 'Customer Receipt',
            'description' => 'Record payment received from customer',
            'category' => 'receipts',
            'component' => \App\Livewire\Admin\Accounts\Entry\Receipts\CustomerReceiptForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::CUSTOMER_RECEIPT,
            'permission' => 'accounts.entry.receipts.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 20,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
            'route' => null,
        ],
        'owner-investment' => [
            'title' => 'Owner Investment',
            'description' => 'Record capital invested by owner',
            'category' => 'receipts',
            'component' => \App\Livewire\Admin\Accounts\Entry\Receipts\OwnerInvestmentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::OWNER_INVESTMENT,
            'permission' => 'accounts.entry.receipts.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 30,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>',
            'route' => null,
        ],
        'loan-received' => [
            'title' => 'Loan Received',
            'description' => 'Record loan received from lender',
            'category' => 'receipts',
            'component' => \App\Livewire\Admin\Accounts\Entry\Receipts\LoanReceivedForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::LOAN_RECEIVED,
            'permission' => 'accounts.entry.receipts.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 40,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="1"/><path d="M12 1v6m0 6v6"/><path d="M4.22 4.22l4.24 4.24m3.08 0l4.24-4.24"/><path d="M4.22 19.78l4.24-4.24m3.08 0l4.24 4.24"/></svg>',
            'route' => null,
        ],
        'advance-receipt' => [
            'title' => 'Advance Receipt',
            'description' => 'Record advance received',
            'category' => 'receipts',
            'component' => \App\Livewire\Admin\Accounts\Entry\Receipts\AdvanceReceiptForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::ADVANCE_RECEIPT,
            'permission' => 'accounts.entry.receipts.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 50,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/></svg>',
            'route' => null,
        ],

        // Payments - Reused Expense Forms
        'project-expense' => [
            'title' => 'Project Expense',
            'description' => 'Expense for a specific project',
            'category' => 'payments',
            'component' => null,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::EXPENSE,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 10,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/></svg>',
            'route' => ['name' => 'admin.accounts.expenses.create', 'params' => ['category' => 'project-expense']],
        ],
        'office-expense' => [
            'title' => 'Office Expense',
            'description' => 'Office-related expense',
            'category' => 'payments',
            'component' => null,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::EXPENSE,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 20,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>',
            'route' => ['name' => 'admin.accounts.expenses.create', 'params' => ['category' => 'office-expense']],
        ],
        'marketing-expense' => [
            'title' => 'Marketing Expense',
            'description' => 'Marketing-related expense',
            'category' => 'payments',
            'component' => null,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::EXPENSE,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 30,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 12 21 12"/><polyline points="3 6 21 6"/><polyline points="3 18 21 18"/></svg>',
            'route' => ['name' => 'admin.accounts.expenses.create', 'params' => ['category' => 'marketing-expense']],
        ],
        'generic-expense' => [
            'title' => 'General Expense',
            'description' => 'General business expense',
            'category' => 'payments',
            'component' => null,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::EXPENSE,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 40,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="1"/></svg>',
            'route' => ['name' => 'admin.accounts.expenses.create', 'params' => ['category' => 'generic-expense']],
        ],

        // Payments - New Forms
        'supplier-payment' => [
            'title' => 'Supplier Payment',
            'description' => 'Payment to supplier',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\SupplierPaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::SUPPLIER_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 50,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
            'route' => null,
        ],
        'owner-withdrawal' => [
            'title' => 'Owner Withdrawal',
            'description' => 'Withdraw capital by owner',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\OwnerWithdrawalForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::OWNER_WITHDRAWAL,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 60,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-4M20.49 15a9 9 0 0 1-14.85 4"/></svg>',
            'route' => null,
        ],
        'loan-repayment' => [
            'title' => 'Loan Repayment',
            'description' => 'Repay loan to lender',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\LoanRepaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::LOAN_REPAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 70,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21.5 2v6h-6M2.5 22v-6h6M2 11.5a10 10 0 0 1 18.8-4.3M22 12.5a10 10 0 0 1-18.8 2.2"/></svg>',
            'route' => null,
        ],
        'salary-payment' => [
            'title' => 'Salary Payment',
            'description' => 'Pay salary to employee',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\SalaryPaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::SALARY_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 80,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 1v22M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>',
            'route' => null,
        ],
        'labor-bill-payment' => [
            'title' => 'Labor Bill Payment',
            'description' => 'Pay labor or contractor bills',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\LaborBillPaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::LABOR_BILL_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 90,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>',
            'route' => null,
        ],
        'equipment-rent-payment' => [
            'title' => 'Equipment Rent Payment',
            'description' => 'Pay equipment rental charges',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\EquipmentRentPaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::EQUIPMENT_RENT_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 100,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg>',
            'route' => null,
        ],
        'transportation-payment' => [
            'title' => 'Transportation Payment',
            'description' => 'Pay transportation or logistics charges',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\TransportationPaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::TRANSPORTATION_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 110,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="5" cy="17" r="3"/><circle cx="19" cy="17" r="3"/><path d="M5 14V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v10"/></svg>',
            'route' => null,
        ],
        'utility-bill-payment' => [
            'title' => 'Utility Bill Payment',
            'description' => 'Pay utility bills (electricity, water, etc.)',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\UtilityBillPaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::UTILITY_BILL_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 120,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 9h12M9 13h6M3 20h18M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z"/></svg>',
            'route' => null,
        ],
        'advance-payment' => [
            'title' => 'Advance Payment',
            'description' => 'Pay advance to vendor or employee',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\AdvancePaymentForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::ADVANCE_PAYMENT,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 130,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="12 3 20 7.5 20 16.5 12 21 4 16.5 4 7.5 12 3"/></svg>',
            'route' => null,
        ],
        'purchase' => [
            'title' => 'Purchase',
            'description' => 'Record purchase transaction',
            'category' => 'payments',
            'component' => \App\Livewire\Admin\Accounts\Entry\Payments\PurchaseForm::class,
            'workflow' => EntryWorkflow::BANKING_REQUEST,
            'transaction_type' => TransactionType::PURCHASE,
            'permission' => 'accounts.entry.payments.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 140,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>',
            'route' => null,
        ],

        // Transfers & Adjustments
        'fund-transfer' => [
            'title' => 'Fund Transfer',
            'description' => 'Transfer funds between accounts',
            'category' => 'transfers',
            'component' => \App\Livewire\Admin\Accounts\Entry\Transfers\FundTransferForm::class,
            'workflow' => EntryWorkflow::DIRECT_LEDGER,
            'transaction_type' => TransactionType::TRANSFER,
            'permission' => 'accounts.entry.transfers.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 10,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"/><polyline points="19 12 12 19 5 12"/></svg>',
            'route' => null,
        ],
        'adjustment' => [
            'title' => 'Adjustment',
            'description' => 'Adjust account balance',
            'category' => 'transfers',
            'component' => \App\Livewire\Admin\Accounts\Entry\Transfers\AdjustmentForm::class,
            'workflow' => EntryWorkflow::DIRECT_LEDGER,
            'transaction_type' => TransactionType::ADJUSTMENT,
            'permission' => 'accounts.entry.transfers.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 20,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>',
            'route' => null,
        ],
        'reverse' => [
            'title' => 'Reverse Entry',
            'description' => 'Reverse a previous transaction',
            'category' => 'transfers',
            'component' => \App\Livewire\Admin\Accounts\Entry\Transfers\ReverseForm::class,
            'workflow' => EntryWorkflow::DIRECT_LEDGER,
            'transaction_type' => TransactionType::REVERSE,
            'permission' => 'accounts.entry.transfers.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 30,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21.5 2v6h-6M2.5 22v-6h6M2 11.5a10 10 0 0 1 18.8-4.3M22 12.5a10 10 0 0 1-18.8 2.2"/></svg>',
            'route' => null,
        ],

        // Opening Balance
        'opening-balance' => [
            'title' => 'Opening Balance',
            'description' => 'Set initial account balances',
            'category' => 'opening',
            'component' => \App\Livewire\Admin\Accounts\Entry\Opening\OpeningBalanceForm::class,
            'workflow' => EntryWorkflow::DIRECT_LEDGER,
            'transaction_type' => TransactionType::OPENING_BALANCE,
            'permission' => 'accounts.entry.opening.create',
            'enabled' => true,
            'visible' => true,
            'sort' => 10,
            'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/></svg>',
            'route' => null,
        ],
    ],
];
